replicaCount: 1

image:
  repository: clamav/clamav 
  tag: "latest"
  pullPolicy: Always 

imagePullSecrets:
  - name: dockerhub-secret

podLabels:
  app: clamav-container  
  tier: backend   

service:
  type: ClusterIP
  port: 3310
  containerPort: 3310
  targetPort: 3310

env:
  enabled: true
  items:
    - name: CLAMD_CONF_MaxFileSize
      value: "100M"
    - name: CLAMD_CONF_MaxScanSize
      value: "100M"
    - name: CLAMD_CONF_StreamMaxLength
      value: "100M" 

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

persistence:
  pv:
    enabled: true
    name: "clamav-pv-test"
    labels:
      type: "local"
    annotations: {}
    storageClassName: "manual"
    reclaimPolicy: "Retain"          
    volumeMode: "Filesystem"
    capacity: "6Gi"
    accessModes:
      - ReadWriteMany
    hostPath:
      path: "/data/clamav"
      type: ""                        
    claimRef:
      enabled: true
      name: "clamav-pvc-test"
      
  pvc:
    enabled: true
    name: "clamav-pvc-test"
    labels:
      type: "local"
    annotations: {}
    storageClassName: "manual"
    volumeMode: "Filesystem"
    accessModes:
      - ReadWriteMany
    size: "6Gi"
    volumeName: "clamav-pv-test"

volumes:
  - name: clamav-volume-mount
    persistentVolumeClaim:
     claimName: clamav-pvc-test

volumeMounts:
  - name: clamav-volume-mount
    mountPath: /data/clamav

# resources:
#   requests:
#     cpu: 300m
#   limits:
#     cpu: 1500m
#--- ohter params -----------

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podSecurityContext: {}

securityContext: {}
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

