{{- $namespace := .Values.namespace | default "default" }}
{{- range $secName, $sec := .Values.secrets }}
{{- if $sec.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secName }}
  namespace: {{ $namespace }}
type: {{ $sec.type | default "Opaque" }}
data:
  {{- range $key, $val := $sec.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
