jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set job-level env

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm chart
        run: helm package ./ainon-helm

      - name: Download secondary repo and update index
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Add here as well for step-level env
        run: |
          git clone https://x-access-token:${REPO_TOKEN}@github.com/SurajZigi/helm-hosting.git temp-helm-repo
          cd temp-helm-repo
          cp ../ainon-helm-*.tgz .
          helm repo index . --url https://SurajZigi.github.io/helm-hosting/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Release new chart version from $GITHUB_SHA" || echo "No changes to commit"
          git push origin main
